
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 17 01:05:10 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 44;
  public static final int CHAR = 49;
  public static final int CONST = 8;
  public static final int CASE = 20;
  public static final int NOTEQUAL = 29;
  public static final int LPAREN = 42;
  public static final int SEMI = 37;
  public static final int GREATER = 30;
  public static final int CONTINUE = 16;
  public static final int GREATEQ = 31;
  public static final int LESS = 32;
  public static final int FOR = 17;
  public static final int MINUS = 24;
  public static final int RPAREN = 43;
  public static final int AND = 34;
  public static final int OR = 35;
  public static final int COMMA = 39;
  public static final int CLASS = 5;
  public static final int INC = 21;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int LESSEQ = 33;
  public static final int IF = 9;
  public static final int DOT = 40;
  public static final int BOOLEAN = 50;
  public static final int ABSTRACT = 6;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int RBRACKET = 45;
  public static final int EQUAL = 28;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int NUMBER = 48;
  public static final int MOD = 27;
  public static final int IDENT = 51;
  public static final int BREAK = 3;
  public static final int VOID = 14;
  public static final int SWITCH = 19;
  public static final int COLON = 38;
  public static final int LBRACE = 46;
  public static final int ELSE = 7;
  public static final int ENUM = 4;
  public static final int READ = 12;
  public static final int RBRACE = 47;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int ASIGN = 36;
  public static final int QUESTION = 41;
  public static final int DEC = 22;
  public static final int PRINT = 11;
  public static final int LENGTH = 18;
}

